---

- name: Create common directories 
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:
    - "dev"
    - "dev/data"
    - "dev/envs"
    - "dev/repos"
    - "dev/tmp"
    - "dev/tools"

- name: Create directories for work
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:
    - "work"
    - "work/data"
    - "work/envs"
    - "work/repos"
    - "work/tmp"
    - "work/tools"
    - "work/docs"
    - "work/docs/notes"
    - "work/docs/orga"
    - "work/docs/papers"
    - "work/docs/templates"
    - "work/docs/wiki"

- name: Create directories for my private stuff
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:
    - "docs"
    - "docs/notes"
    - "docs/orga"
    - "docs/papers"
    - "docs/templates"
    - "docs/wiki"

