language: python
python:
  - 3.6
git:
  depth: 1
  quiet: true
  submodules: false

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - git submodule update --init --recursive
  - sudo apt-get update -qq
install:
  - pip install ansible
script:
  - ansible-playbook main.yml
