sudo: required

services:
- docker

arch:
  packages:
  - ansible
  script:
  - ansible-playbook main.yml

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
