---
- hosts: localhost

  vars:
    work: "{{ lookup('env', 'work') }}"
    ruby_version: 2.5.0
    python2_version: 2.7.15
    python3_version: 3.6.2
    python_versions: [python2_version, python3_version]

  roles:
    - { role: 'desktop', tags: 'desktop' }
    - { role: 'dirs', tags: 'dirs' }
    - { role: 'dotfiles', tags: 'dotfiles' }
    - { role: 'fonts', tags: 'fonts' }
    - { role: 'mail', tags: 'mail' }
    - { role: 'news', tags: 'news' }
    - { role: 'nvim', tags: 'nvim' }
    - { role: 'qutebrowser', tags: 'qutebrowser' }
    - { role: 'ranger', tags: 'ranger' }
    - { role: 'rofi', tags: 'rofi' }
    - { role: 'terminfo', tags: 'terminfo' }
    - { role: 'zsh', tags: 'zsh' }
