---
- hosts: localhost

  vars:
    work: "{{ lookup('env', 'work') }}"
  roles:
    - { role: 'terminfo', tags: 'terminfo' }
    - { role: 'dirs', tags: 'dirs' }
    - { role: 'fonts', tags: 'fonts' }
    - { role: 'news', tags: 'news' }
    - { role: 'dotfiles', tags: 'dotfiles' }
    - { role: 'nvim', tags: 'nvim' }
    - { role: 'ruby', tags: 'ruby' }
    - { role: 'python', tags: 'python' }
    - { role: 'java', tags: 'java' }
    - { role: 'mail', tags: 'mail' }
