---
- name: Create XDG config directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: Create symlinks of stored dotfiles not in the config folder
  file:
    src: "{{ role_path }}/files/{{ item }}"
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - "{{ dotfiles }}"
