---
- name: Create XDG config directory
  file: 
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: Create nvim autoload directory
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim/autoload"
    state: directory

- name: Install nvim plugin manager
  get_url: 
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/autoload/"

- name: Create symlinks of stored dotfiles not in the config folder
  file: 
    src: "{{ role_path }}/files/{{ item }}"
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - "{{ dotfiles }}"
