---

- name: Link pyenv
  file:
    path: "{{ ansible_env.HOME }}/.pyenv"
    src: "{{ role_path }}/files/pyenv"
    state: link

- name: Install shim
  file:
    path: "{{ ansible_env.HOME }}/.zsh/shims/python.sh"
    src: "{{ role_path }}/files/python.sh"
    state: link

- name: Install Python 2
  command: "pyenv install --skip-existing {{ python2_version }}"
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ python2_version }}"

- name: Install Python 3
  command: "pyenv install --skip-existing {{ python3_version }}"
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ python3_version }}"

- name: Use Python 3 as default
  command: "pyenv global {{ python3_version }}"

- name: Install virtualenv
  pip: executable=pip3 name=virtualenv
