---

- name: Create XDG config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/"
    state: directory

- name: Link offlineimap/alot configuration files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: link
  with_items:
    - alot

- name: Link remaining configuration files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
  with_items:
    - .msmtprc
    - .mbsyncrc
    - .notmuch-config
    - .mailcap

- name: Create scripts directory
  file:
    path: "{{ ansible_env.HOME }}/.scripts/"
    state: directory

- name: Link notmuch taggint script
  file:
    src: "{{ role_path }}/files/notmuch-tagging.sh"
    dest: "{{ ansible_env.HOME }}/.scripts/notmuch-tagging.sh"
    state: link
    mode: 0755
