---

- name: Link mutt configuration files
  file:
    src: "{{ role_path }}/files/mutt"
    dest: "{{ ansible_env.HOME }}/.mutt"
    state: link

- name: Create XDG config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/"
    state: directory

- name: Link offlineimap configuration files
  file:
    src: "{{ role_path }}/files/offlineimap"
    dest: "{{ ansible_env.HOME }}/.config/offlineimap"
    state: link

- name: Link remaining configuration files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
  with_items:
    - .msmtprc
