---

- name: Link rbenv
  file:
    path: "{{ ansible_env.HOME }}/.rbenv"
    src: "{{ role_path }}/files/rbenv"
    state: link

- name: Install shim
  file:
    path: "{{ ansible_env.HOME }}/.zsh/shims/ruby.sh"
    src: "{{ role_path }}/files/ruby.sh"
    state: link

- name: Make rbenv plugin folder
  file: 
    path: "{{ role_path }}/files/rbenv/plugins"
    state: directory

- name: Link rbenv plugin ruby-build
  file:
    path: "{{ role_path }}/files/rbenv/plugins/ruby-build"
    src: "{{ role_path }}/files/ruby-build"
    state: link
